## Cleaning up resources
```cpp
#include <iostream>

try
{
    openFile(filename);
    writeFile(filename, data);
    //closeFile(filename); Exception would cause file to never be closed and memory leak.
}
catch (const FileException& exception)
{
    std::cerr << "Failed to write to file: " << exception.what() << '\n';
}

// Make sure file is closed
closeFile(filename);
```

```cpp
#include <iostream>

Person* john{ nullptr };

try
{
	//Person* john{ nullptr }; Exception would cause memory leak.
    john = new Person("John", 18, PERSON_MALE);
    processPerson(john);
}
catch (const PersonException& exception)
{
    std::cerr << "Failed to process person: " << exception.what() << '\n';
}

delete john;
```

```cpp
#include <iostream>
#include <memory> // for std::unique_ptr

try
{
    auto* john { new Person("John", 18, PERSON_MALE) };
    std::unique_ptr<Person> upJohn { john }; // upJohn now owns john. Automatic deallocation.

    ProcessPerson(john);

    // when upJohn goes out of scope, it will delete john
}
catch (const PersonException& exception)
{
    std::cerr << "Failed to process person: " << exception.what() << '\n';
}
```

## Exceptions and destructors
Exceptions should never be thrown in destructors.

When an exception is thrown from a destructor during the stack unwinding process, the compiler does not know whether to keep unwinding the stack or to handle the new exception.

## Performance concerns
Exceptions increase the size of executables.

Executables are slower because of additional checking that has to be performed.

Unwinding the stack and finding a matching exception handler are expensive operations.

## When to use exceptions
Exception handling should be used when:
- The error being handled is likely to occur only infrequently.
- The error is serious and execution could not continue otherwise.
- The error cannot be handled at the place where it occurs.
- There are no good alternatives to exception handling.
